"""empty message

Revision ID: 2b33935b5de7
Revises: eda4ac5304c8
Create Date: 2023-06-30 10:58:28.798239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b33935b5de7'
down_revision = 'eda4ac5304c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.alter_column('card', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.alter_column('card', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
