"""empty message

Revision ID: 6176c6bda3f4
Revises: 820d94f1037c
Create Date: 2023-06-27 13:04:04.572628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6176c6bda3f4'
down_revision = '820d94f1037c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
