"""empty message

Revision ID: b035d26dd4c8
Revises: 98c1ff20038a
Create Date: 2023-06-24 16:39:10.884443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b035d26dd4c8'
down_revision = '98c1ff20038a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('board', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.alter_column('card', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.alter_column('card', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('card', 'board_id')
    op.alter_column('board', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('board', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
