"""add additional attributes and create relationship between card and board

Revision ID: bf3f44eef285
Revises: bd74c4a69c80
Create Date: 2023-06-26 18:13:42.021707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3f44eef285'
down_revision = 'bd74c4a69c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('description', sa.String(), nullable=True))
    op.add_column('board', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('board', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('card', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    op.drop_column('card', 'date_created')
    op.drop_column('board', 'date_created')
    op.drop_column('board', 'theme')
    op.drop_column('board', 'description')
    # ### end Alembic commands ###
