"""card and board models added

Revision ID: d10e5fafbb21
Revises: 
Create Date: 2023-06-26 15:03:53.669336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10e5fafbb21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('board_id', name='board_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('card',
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], name='card_board_id_fkey'),
    sa.PrimaryKeyConstraint('card_id', name='card_pkey')
    )
    # ### end Alembic commands ###
